# Generated by Django 5.1.5 on 2025-01-23 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_categoria_funcionario_carta_apresentacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='senioridade',
            new_name='nome',
        ),
    ]
