# Generated by Django 5.1.5 on 2025-01-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=20)),
                ('tipo_de_constituicao', models.CharField(max_length=100)),
                ('valor_de_mercado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_fundacao', models.DateField()),
            ],
        ),
    ]
